version: '2'
services:
  myapp-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/myapp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=myapp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
